server:
    port: 9090

spring:
  application:
    name: restaurant
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: mysql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "https://login.microsoftonline.com/4675797b-3a63-4c13-8ab3-1ba08ff829d0/discovery/v2.0/keys"

order:
  service:
    baseUri: http://localhost:9091/api/orders

management:
  endpoints:
    web:
      exposure:
        include: env, health

#  cloud:
#    config:
#      uri:
#      - http://localhost:8888
#      username: config_username
#      password: config_password
#      fail-fast: true
#      label: master
#  profiles:
#    active:
#    - dev