server:
    port: 9090

spring:
  application:
    name: restaurant
  data:
    mongodb:
      host: localhost
      port: 27017
      database: restaurant

log4j:
  category:
    org:
      springframework:
        data:
          mongodb: DEBUG
  appender:
    stdout:
      layout:
        ConversionPattern: '%d{ABSOLUTE} %5p %40.40c:%4L - %m%n'

order:
  service:
    baseUri: http://localhost:9091/api/orders

management:
  endpoints:
    web:
      exposure:
        include: env, health

#  cloud:
#    config:
#      uri:
#      - http://localhost:8888
#      username: config_username
#      password: config_password
#      fail-fast: true
#      label: master
#  profiles:
#    active:
#    - dev