server:
  port: 9091

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: mysql
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: env, health