server:
  port: 9091

spring:
  application:
    name: order
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders

log4j:
  category:
    org:
      springframework:
        data:
          mongodb: DEBUG
  appender:
    stdout:
      layout:
        ConversionPattern: '%d{ABSOLUTE} %5p %40.40c:%4L - %m%n'

management:
  endpoints:
    web:
      exposure:
        include: env, health