server:
  port: 8889

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: restaurants
          uri: http://localhost:9090
          predicates:
            - Path=/api/restaurants/**
        - id: orders
          uri: http://localhost:9091
          predicates:
            - Path=/api/orders/**

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
      core:
        codec:
          StringDecoder: TRACE